- name: "~/.nanorc"
  application: "Nano"
  url: "https://github.com/Console-Utils/editor-configs/blob/main/.nanorc"
- name: "~/.vimrc"
  application: "Vim"
  logo: "vim"
  url: "https://github.com/Console-Utils/editor-configs/blob/main/.vimrc"
- name: "~/.bashrc"
  application: "Bash"
  logo: "gnubash"
  url: "https://github.com/Console-Utils/bash-configs"
- name: "config.fish"
  application: "Fish"
  url: "https://github.com/Console-Utils/fish-configs"
