- name: "Repl.it"
  url: "https://replit.com/@EmilySeville7cfg"
- name: "Reddit"
  url: "https://www.reddit.com/user/EmilySeville7cfg"
- name: "Telegram"
  url: "https://t.me/emilyseville7cfg"
- name: "Skype"
  url: "https://join.skype.com/invite/WMeGcqvpRVeW"
- name: "VK"
  url: "https://vk.com/emilyseville7cfg"
  visible: false
- name: "SoundCloud"
  url: "https://soundcloud.com/emilyseville7cfg"
